import type { Config } from 'tailwindcss'

export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--canvas)',
        'canvas-strong': 'var(--canvas-strong)',
        surface: 'var(--surface)',
        card: 'var(--card)',
        'card-muted': 'var(--card-muted)',
        foreground: 'var(--foreground)',
        'secondary-foreground': 'var(--secondary-foreground)',
        'muted-foreground': 'var(--muted-foreground)',
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-foreground': 'var(--primary-foreground)',
        brand: 'var(--brand)',
        'brand-soft': 'var(--brand-soft)',
        warning: 'var(--warning)',
        'warning-strong': 'var(--warning-strong)',
        'warning-soft': 'var(--warning-soft)',
        'warning-foreground': 'var(--warning-foreground)',
        danger: 'var(--danger)',
        'danger-hover': 'var(--danger-hover)',
        'danger-soft': 'var(--danger-soft)',
        'danger-foreground': 'var(--danger-foreground)',
        destructive: 'var(--destructive-background)',
        'destructive-hover': 'var(--destructive-hover)',
        'destructive-foreground': 'var(--destructive-foreground)',
        success: 'var(--success)',
        'success-soft': 'var(--success-soft)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        ring: 'var(--ring)',
        'zinc-900': 'var(--zinc-900)',
        'zinc-700': 'var(--zinc-700)',
        'zinc-600': 'var(--zinc-600)',
        'zinc-400': 'var(--zinc-400)',
        'zinc-300': 'var(--zinc-300)',
        'zinc-door': 'var(--zinc-door)',
      },
      backgroundImage: {
        'primary-action': 'var(--primary-gradient)',
        'primary-action-hover': 'var(--primary-gradient-hover)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
      },
      boxShadow: {
        rest: 'var(--shadow-rest)',
        float: 'var(--shadow-float)',
        hover: 'var(--shadow-hover)',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      transitionTimingFunction: {
        vault: 'cubic-bezier(.22, 1, .36, 1)',
      },
      transitionDuration: {
        micro: '160ms',
        default: '240ms',
        page: '320ms',
      },
    },
  },
  plugins: [],
} satisfies Config
